"""initial tables

Revision ID: 55ea28592a60
Revises: 
Create Date: 2026-03-09 11:26:51.309548
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '55ea28592a60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('building_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('detection_method', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anomaly_building_time', 'anomaly_events', ['building_id', 'timestamp'], unique=False)
    op.create_index('idx_anomaly_severity', 'anomaly_events', ['severity', 'resolved'], unique=False)
    op.create_index(op.f('ix_anomaly_events_building_id'), 'anomaly_events', ['building_id'], unique=False)
    op.create_index(op.f('ix_anomaly_events_timestamp'), 'anomaly_events', ['timestamp'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('building_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('building_type', sa.String(length=64), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('area > 0', name='ck_building_area_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_building_type', 'buildings', ['building_type'], unique=False)
    op.create_index(op.f('ix_buildings_building_id'), 'buildings', ['building_id'], unique=True)
    op.create_table('energy_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('electricity_kwh', sa.Float(), nullable=True),
    sa.Column('water_m3', sa.Float(), nullable=True),
    sa.Column('gas_m3', sa.Float(), nullable=True),
    sa.Column('hvac_kwh', sa.Float(), nullable=True),
    sa.Column('hvac_supply_temp', sa.Float(), nullable=True),
    sa.Column('hvac_return_temp', sa.Float(), nullable=True),
    sa.Column('hvac_flow_rate', sa.Float(), nullable=True),
    sa.Column('outdoor_temp', sa.Float(), nullable=True),
    sa.Column('outdoor_humidity', sa.Float(), nullable=True),
    sa.Column('occupancy_density', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.CheckConstraint('electricity_kwh IS NULL OR electricity_kwh >= 0', name='ck_energy_electricity_positive'),
    sa.CheckConstraint('hvac_flow_rate IS NULL OR hvac_flow_rate >= 0', name='ck_energy_flow_positive'),
    sa.CheckConstraint('hvac_kwh IS NULL OR hvac_kwh >= 0', name='ck_energy_hvac_positive'),
    sa.CheckConstraint('water_m3 IS NULL OR water_m3 >= 0', name='ck_energy_water_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_energy_building_time', 'energy_records', ['building_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_energy_records_building_id'), 'energy_records', ['building_id'], unique=False)
    op.create_index(op.f('ix_energy_records_timestamp'), 'energy_records', ['timestamp'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('building_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('rated_power_kw', sa.Float(), nullable=True),
    sa.Column('install_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_index(op.f('ix_equipment_building_id'), 'equipment', ['building_id'], unique=False)
    op.create_table('equipment_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('power_consumption_kw', sa.Float(), nullable=True),
    sa.Column('runtime_hours', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_equip_status_device_time', 'equipment_status', ['device_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_equipment_status_device_id'), 'equipment_status', ['device_id'], unique=False)
    op.create_index(op.f('ix_equipment_status_timestamp'), 'equipment_status', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_status_timestamp'), table_name='equipment_status')
    op.drop_index(op.f('ix_equipment_status_device_id'), table_name='equipment_status')
    op.drop_index('idx_equip_status_device_time', table_name='equipment_status')
    op.drop_table('equipment_status')
    op.drop_index(op.f('ix_equipment_building_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_energy_records_timestamp'), table_name='energy_records')
    op.drop_index(op.f('ix_energy_records_building_id'), table_name='energy_records')
    op.drop_index('idx_energy_building_time', table_name='energy_records')
    op.drop_table('energy_records')
    op.drop_index(op.f('ix_buildings_building_id'), table_name='buildings')
    op.drop_index('idx_building_type', table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_anomaly_events_timestamp'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_building_id'), table_name='anomaly_events')
    op.drop_index('idx_anomaly_severity', table_name='anomaly_events')
    op.drop_index('idx_anomaly_building_time', table_name='anomaly_events')
    op.drop_table('anomaly_events')
    # ### end Alembic commands ###
